def get_pic(mark):
    a=Pildid.index(mark)
    return "pics/"+Pildid[a+1]
Pildid=["#","_2.gif",
        "U","up.gif",
        "D","down.gif",
        "Q","quit.gif",
        "L","left.gif",
        "R","right.gif",
        " ","Taust.gif",
        "attack","shield.gif",
        "defence","atk.gif",
        "p","pot.gif",
        "s","wep.gif",
        "b","Stick.gif",
        "m","armor.gif",
        "c","cloak.gif",
        ".","punkt.gif",
        "0","pot0.gif",
        "1","pot1.gif",
        "2","pot2.gif",
        "3","pot3.gif",
        "4","pot4.gif",
        "5","pot5.gif",
        "fem","f.gif",
        "male","m.gif",
        "T","teddy.gif",
        "H","mihkel_hunter.gif",
        "M","mummy.gif",
        "B","something_bad_guy.gif"]
