def get_pic(mark):
    a=Pildid.index(mark)
    return "pics/"+Pildid[a+1]
Pildid=["#","_2.gif",
        "U","up.gif",
        "D","down.gif",
        "Q","quit.gif",
        "L","left.gif",
        "R","right.gif",
        " ","Taust.gif",
        "a","shield.gif",
        "d","atk.gif",
        "h","pot.gif",
        "Sword","wep.gif",
        "Stick","Stick.gif",
        "Chainmail","armor.gif",
        "Cloak","cloak.gif",
        ".","punkt.gif",
        "N","shield.gif",
        "0","pot0.gif",
        "1","pot1.gif",
        "2","pot2.gif",
        "3","pot3.gif",
        "4","pot4.gif",
        "5","pot5.gif",
        "f","f.gif",
        "m","m.gif",
        "T","teddy.gif",
        "H","mihkel_hunter.gif",
        "M","mummy.gif",
        "B","something_bad_guy.gif"]
